-- +goose Up
-- +goose StatementBegin
-- This migration generates slugs for existing equipment items
-- Slugs are generated by converting names to lowercase and replacing spaces/underscores with hyphens
-- Note: This is a simplified version. For more complex slug generation, use the Go seed script
UPDATE equipment_items 
SET slug = LOWER(REPLACE(REPLACE(REPLACE(name, ' ', '-'), '_', '-'), '--', '-'))
WHERE slug IS NULL OR slug = '';

-- Trim leading/trailing hyphens manually for common cases
UPDATE equipment_items 
SET slug = TRIM(BOTH '-' FROM slug)
WHERE slug IS NOT NULL AND (slug LIKE '-%' OR slug LIKE '%-');

-- Add unique constraint on slug (only for non-deleted items)
CREATE UNIQUE INDEX idx_equipment_items_slug_unique ON equipment_items(slug) 
WHERE deleted_at IS NULL AND slug IS NOT NULL;
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP INDEX IF EXISTS idx_equipment_items_slug_unique;
-- +goose StatementEnd







